### ISSUE TITLE
Step0 - User can connect to polkadot.js 

### ISSUE THREAD

**Issue by Redoudou** [ChainSafe/filecoindot#145]
When user clic on `connect to polkadot.js` on FSB-WEB homepage they connect to their polkadot.js wallet and the hash of their wallet will display in the field hash_of_the_wallet

![image.png](https://images.zenhubusercontent.com/583c166cb9dc3c622022967a/aa8a2eb9-a712-4622-8149-2cdbaddf12e6)

**Comment by Tbaut** [comment]
closed in https://github.com/ChainSafe/filecoindot/pull/149
