### ISSUE TITLE
Step1 - Test CID

### ISSUE THREAD

**Issue by Redoudou** [ChainSafe/filecoindot#148]
After being connected to the network and the node, the user can give the NFT a name, a CID. This CID must be a filecoin "deal proof".
When the user click on the button Test CID Deal Proof the web page will run the verify proof of filecoindot.
![image.png](https://images.zenhubusercontent.com/583c166cb9dc3c622022967a/8642348d-9086-4b05-94f3-7180240a7987)

If the deal proof is valid then user will be sent to step 3.1
![image.png](https://images.zenhubusercontent.com/583c166cb9dc3c622022967a/0bd35fd4-de2f-4a7b-9dcb-1198ec75b9f7)

if the deal proof is invalid the user will be sent to step 3.0
![image.png](https://images.zenhubusercontent.com/583c166cb9dc3c622022967a/321af04e-c9a6-4c5c-8ce0-f22ae4cba87e)

The client understand that the user will have to submit a deal proof.

**Comment by Tbaut** [comment]
closed in https://github.com/ChainSafe/filecoindot/pull/149
