### ISSUE TITLE
Setp 3.1 - Valid CID > Minting NFT

### ISSUE THREAD

**Issue by Redoudou** [ChainSafe/filecoindot#152]
When the User provides a valid CID, they reach to the following page 
![image.png](https://images.zenhubusercontent.com/583c166cb9dc3c622022967a/804eb07e-dcac-4451-86d1-d546f9fee5a2)

User can click on Mint NFT to create a NFT associated to that CID. 

_We understand here the CID is not the CID of a file uploaded on to IPFS but a deal proof CID. Also called piece CID by @rvagg in our design documents _

**Comment by Tbaut** [comment]
closes by
