### ISSUE TITLE
Proof Validation CLI

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/filecoindot#2]
## Implementation details

Add cargo installable executeable that can validate proofs.
## Acceptance Criteria

- [ ] Proof can be validated by a Rust test command line tool that wraps the verification crate.

Commands
- `verify` that accepts a proof in hex form, supports multiple proofs as arguments, either as direct inputs or read from a file

**Comment by mattsse** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Filecoin-Substrate-Bridge-615c54b651ea630016bdf5aa/issues/ChainSafe/filecoindot/2?planning-poker) with ZenHub @ivanceras

**Comment by ivanceras** [comment]
@mattsse 
> supports multiple proofs as arguments
Isn't supposed to be multiple CID to verify that it belongs in one proof?
