### ISSUE TITLE
Adds off chain worker for submitting voting txs

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/filecoindot#27]
## Issue summary

- [ ] Add off-chain worker functionality to pallet which polls a trusted Filecoin RPC for latest final blocks and submits vote transactions
- [ ] The Worker is executed every block but will only submit votes for new, finalized blocks that this node has not yet cast a vote for. Vote transactions are signed by the nodes local worker keys configured in the keystore
- [ ] New Filecoin blocks are automatically voted on in signed transactions. If the worker keys are registered in the relayer set then these votes are accepted.

## Other information and links

-

**Comment by mattsse** [comment]
@clearloop  what's missing from this task list?

**Comment by clearloop** [comment]
> @clearloop what's missing from this task list? Can this be closed?

can be closed now
