### ISSUE TITLE
Add example runtime and node that uses bridge pallet

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/filecoindot#7]
## Implementation details

- [ ] use the substrate-node template for an example that implements the bridge pallet

- See also [chainlink-pallet and example](https://github.com/smartcontractkit/chainlink-polkadot)
## Acceptance Criteria

- Provide additional documentation on how to configure the pallet
- Provide run instructions

**Comment by clearloop** [comment]
Closed in #43
