### ISSUE TITLE
optimize proposal storage layout

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/filecoindot#73]
Currently, we track the votes within the proposal type as

https://github.com/ChainSafe/filecoindot/blob/56acb76b0f033b372cc38558c1181b27a62d148c/filecoindot/src/types.rs#L16

used in the submit_block_vote extrinsic

https://github.com/ChainSafe/filecoindot/blob/f3c3dbf7d76a07a231d0e411c5e2890a09d83a7f/filecoindot/src/lib.rs#L256

To optimize this we could track the votes in a separate map (Block, Vec<Votes>) or double map (Block, Accounte, Vote) for votes only.
Should be pruned after block is finalized.

**Comment by ivanceras** [comment]
@mattsse as I understand it, we are going to make a separate storage for the votes for a coresponding block proposal, then when that particular block gets finalized (via `fn finalize_block`), we also remove that data which is the list of accounts that votes for the block that was finalized.
