### ISSUE TITLE
docker deployment in CI

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/filecoindot#79]
## Issue summary

- 

## Other information and links

-

**Comment by clearloop** [comment]
This requires a docker secret setting for filecoindot

- create a repository in dockerhub `ChainSafe/filecoindot`
- set the secrets to the settings 
  -  `secrets.DOCKERHUB_USERNAME`
  -  `secrets.DOCKERHUB_TOKEN`

@Redoudou  @mattsse

**Comment by Redoudou** [comment]
@GregTheGreek I think you are the only one that can open docker repo for us. Can you help ? thank you
