### ISSUE TITLE
Ensure vote transaction triggered in e2e tests

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/filecoindot#98]
## Issue summary

in case of the test in this issue is hard to debug ( http requests have problem in production rn ), the implementation of #97 only tested the `add_relayer` transaction, need a follow up on this problem.

## Other information and links
-

**Comment by clearloop** [comment]
Getting `403 Forbidden` only in ocw rn

**Comment by mattsse** [comment]
wonder if we should use a lotus/forest image for e2e tests or somehow connect to testnet?

**Comment by clearloop** [comment]
> wonder if we should use a lotus/forest image for e2e tests or somehow connect to testnet?

it would be nice if there is a testnet

testing with lotus/forest images have problems that our testing local node need to sync for a while

I'm trying to test with a local forest node, this problem still exists rn, mb it's caused by some configurations of the http client of substrate
